# Práctica Clase 6

1) Cargar el dataset "Emisiones_CO2.csv" provisto en la clase 2 en un Dataframe de Pandas, quitar los registros que contengan valores faltantes e implementar una nueva columna, que contenga el resultado de una función Hash aplicada sobre el campo "Código de País" y se denomine "Clave_Hash".<br>
Consideraciones: Se puede utilizar la función provista.

In [77]:
def hash_function(key):
    return sum(index * ord(character) for index, character in enumerate(repr(key), start=1))

In [ ]:
print(hash_function('pato'))
print(hash_function('tapo'))

In [78]:
import pandas as pd

In [81]:
df = pd.read_csv('Emisiones_CO2.csv',sep='|',decimal=',', encoding='latin-1')

In [85]:
df.dropna()

,Código de país,Nombre del país,Región,Año,CO2 (kt),CO2 per cápita (toneladas métricas),Clave_Hash
26,ABW,Aruba,América Latina y Caribe,1986,"179,683",2.868319,910
27,ABW,Aruba,América Latina y Caribe,1987,"447,374",7.234964,910
28,ABW,Aruba,América Latina y Caribe,1988,"612,389",10.026508,910
29,ABW,Aruba,América Latina y Caribe,1989,"649,059",10.634733,910
30,ABW,Aruba,América Latina y Caribe,1990,"1.840,83",29.620165,910
...,...,...,...,...,...,...,...
11122,ZWE,Zimbabue,África subsahariana,2007,"9.732,22",0.731867,951
11123,ZWE,Zimbabue,África subsahariana,2008,"7.682,37",0.569255,951
11124,ZWE,Zimbabue,África subsahariana,2009,"8.239,75",0.600521,951
11125,ZWE,Zimbabue,África subsahariana,2010,"9.028,15",0.646073,951
11126,ZWE,Zimbabue,África subsahariana,2011,"9.860,56",0.691698,951

In [86]:
df['Clave_Hash'] = [hash_function(i) for i in df['Código de país']] #se puede usar apply. 
#df['Clave_Hash'] = df['Codifgo de pais'].apply(hash_function)

In [87]:
pd.DataFrame(df)

,Código de país,Nombre del país,Región,Año,CO2 (kt),CO2 per cápita (toneladas métricas),Clave_Hash
0,ABW,Aruba,América Latina y Caribe,1960,NaN,NaN,910
1,ABW,Aruba,América Latina y Caribe,1961,NaN,NaN,910
2,ABW,Aruba,América Latina y Caribe,1962,NaN,NaN,910
3,ABW,Aruba,América Latina y Caribe,1963,NaN,NaN,910
4,ABW,Aruba,América Latina y Caribe,1964,NaN,NaN,910
...,...,...,...,...,...,...,...
11122,ZWE,Zimbabue,África subsahariana,2007,"9.732,22",0.731867,951
11123,ZWE,Zimbabue,África subsahariana,2008,"7.682,37",0.569255,951
11124,ZWE,Zimbabue,África subsahariana,2009,"8.239,75",0.600521,951
11125,ZWE,Zimbabue,África subsahariana,2010,"9.028,15",0.646073,951
11126,ZWE,Zimbabue,África subsahariana,2011,"9.860,56",0.691698,951

In [88]:
pd.DataFrame(df).to_csv('Emisiones_CO2(1).csv', index=False)

2. A partir del Dataframe creado en el punto 1, construir uno nuevo, que contenga solo los valores distintos de la tupla "Clave_Hash", "Código de País" , "Nombre de país" y "Región". Quitando luego del dataframe original los campos "Código de País" , "Nombre de país" y "Región"

In [89]:
df1 = pd.DataFrame(df.iloc[:,[0,1,2,6]].drop_duplicates()) 
#el iloc funciona asi: 
#iloc([fila][columna]) las filas le digo que sean todas, por eso :
                    # las columnas solo las que me pide. 
#luego que me tire las duplicadas.

In [91]:
df = df.drop(['Código de país','Nombre del país','Región'],axis=1) #elimino del original esas 3 columnas. Las voy a dejar en el nuevo.

In [94]:
df

        Año  CO2 (kt)  CO2 per cápita (toneladas métricas)  Clave_Hash
0      1960       NaN                                  NaN         910
1      1961       NaN                                  NaN         910
2      1962       NaN                                  NaN         910
3      1963       NaN                                  NaN         910
4      1964       NaN                                  NaN         910
...     ...       ...                                  ...         ...
11122  2007  9.732,22                             0.731867         951
11123  2008  7.682,37                             0.569255         951
11124  2009  8.239,75                             0.600521         951
11125  2010  9.028,15                             0.646073         951
11126  2011  9.860,56                             0.691698         951

[11127 rows x 4 columns]

In [92]:
print(df1)

      Código de país                Nombre del país  \
0                ABW                          Aruba
52               AND                        Andorra
104              AFG                     Afganistán
156              AGO                         Angola
208              ALB                        Albania
...              ...                            ...
10867            YEM                          Yemen
10919            ZAF                      Sudáfrica
10971            COD  Congo (República Democrática)
11023            ZMB                         Zambia
11075            ZWE                       Zimbabue

                                Región  Clave_Hash
0              América Latina y Caribe         910
52               Europa y Asia Central         870
104                        Sur de Asia         858
156                África subsahariana         893
208              Europa y Asia Central         856
...                                ...         ...
10867  Oriente Medio y Norte de África         927
10919              África subsahariana         889
10971              África subsahariana         877
11023              África subsahariana         909
11075              África subsahariana         951

[214 rows x 4 columns]

In [93]:
pd.DataFrame(df1).to_csv('Emisiones_CO2_corta.csv', index=False)